### ISSUE TITLE
Duplicating a collection object doesn't create a new id

### ISSUE THREAD

**Issue by hanrelan** [antondb/netlify-cms-widget-uuid#2]
When I use "Publish and duplicate" on a collection object, the uuid of the new object is the same as the old one (and can't be changed). It'd be awesome if there was an option so that duplication would result in a new id, since in my case these ids are being used as the ids in a database and must be unique.

Thanks for the great work!

**Comment by antondb** [comment]
Thanks for the feedback, I'll take a look to see what would be involved in adding this.

**Comment by antondb** [comment]
Hi, I have pushed an update that adds a button to regenerate the ID. This should sort the problem out where the copy has the same ID.
